check hw6
etrehappy/otus_cpp_basic_hw6 pull request #1
Opened 2024-02-23 18:44 UTC by etrehappy

Выполнены основное и дополнительные задания

2024-02-23 18:51 UTC, etrehappy commented on source/u_vector.h
> +        return lhs.m_iterator_ptr != rhs.m_iterator_ptr;
Пытался долго разобраться, но так и не понял, как вынести определение отдельно от места объявления. Хотел сделать по аналогии со стр. 26-27 в u_vector.h, но появляется ошибка

Текст ошибки
```
Error  LNK2019  
unresolved external symbol  "bool __cdecl operator!=(struct u_vector<int>::iterator &,struct u_vector<int>::iterator &)" (??9@YA_NAEAUiterator@?$u_vector@H@@0@Z) 
referenced in function      "void __cdecl check_iterator<class u_vector<int> >(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class u_vector<int> const &)" 
(??$check_iterator@V?$u_vector@H@@@@YAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$u_vector@H@@@Z)  
containers  C:\Users\etreh\Documents\Programming\Otus\C++_Developer_2023_06\Basic\lesson_14\otus_cpp_basic_hw6\cmake_build\main.obj  1
```

Есть такой альтернативный вариант, но это уже член класса, а не friend
```
template<typename T>
bool u_vector<T>::iterator::operator!=(typename u_vector<T>::iterator& rhs)
{
    return  m_iterator_ptr != rhs.m_iterator_ptr;
}
```

На уроке говорили, что бинарные операторы должны быть НЕ членами класса. Подскажете, как можно сделать?

2024-02-26 20:10 UTC, MarinaPaley requested changes
Только из-за одного места, где ругался VS. Кажется, что теряете память (течет) при такой реализации.
В остальном - все отлично.

2024-02-26 20:10 UTC, MarinaPaley commented on source/u_vector.ipp
> +    std::copy(arr_old, arr_old + old_size, m_arr); //Использую std::copy, потому что VS не нравится мой код ниже (Warning C6386)
Мне тоже не нравится, только код сверху)
```cpp
auto new_array = new T[m_capacity]{ 0 };
for (size_t i = 0; i < old_size; ++i) // только, если Вы везде поменяете на size_t, иначе int
{
    new_array[i] = m_arr[i];
}

delete[] m_arr;
m_arr = new_array;

2024-03-07 08:34 UTC, etrehappy commented on source/u_forward_list.h
> +    int size() const;
Спасибо, исправил. 

Использовал сначала int, так как знаю, что для целей ДЗ больше и не понадобится)

2024-03-07 08:34 UTC, etrehappy commented on source/u_vector.h
> +        return lhs.m_iterator_ptr != rhs.m_iterator_ptr;
Спасибо за подсказку. Сделал членами класса.

2024-03-07 08:36 UTC, etrehappy commented on source/u_forward_list.h
> +    Node* m_lust_node; //для push_back и end
Конечно) Неожиданный перевод у lust

2024-03-07 08:40 UTC, etrehappy commented on source/u_forward_list.cpp
> +    std::cout << "\n 1. Cоздан объект класса u_forward_list для хранения элементов типа int в контейнере типа «Однонаправленный список».";
Спасибо за совет. Да, это только для наглядности и чтобы не создавать отдельную функцию где-нибудь в main для печати этого текста.

2024-03-07 09:08 UTC, etrehappy commented on source/u_forward_list.cpp
> +    rhs.m_arr_size = 0;
Согласен, добавил метод move_from

2024-03-07 09:18 UTC, etrehappy commented on source/u_forward_list.cpp
> +    new_node->m_data = value;
Спасибо, исправил.

2024-03-07 11:24 UTC, etrehappy commented on source/u_vector.ipp
> +    return m_arr[i];
Добавил проверку в ДЗ.

2024-03-07 11:29 UTC, etrehappy commented on source/u_vector.ipp
> +void u_vector<T>::new_container(const int old_size) {
Таким образом хотел показать, что нигде не используется копирование. И не хотел описывать конструктор копирования, так как это не требовалось в задании (а "= default" не подойдет).

2024-03-07 11:38 UTC, etrehappy commented on source/u_vector.ipp
> +    std::copy(arr_old, arr_old + old_size, m_arr); //Использую std::copy, потому что VS не нравится мой код ниже (Warning C6386)
Спасибо, так выглядит более привычно, наверное. Использовал этот вариант, он, наверное, будет быстрее std::copy, но MSVC всё равно показывает Warning C6386. Как понимаю, он считает, что я могу выйти за границы массива, но я это проверял.

2024-03-07 15:34 UTC, etrehappy commented on source/u_vector.ipp
> +u_vector<T>::u_vector(u_vector<T>&& rhs) noexcept  //доп. задание 3
Согласен, использую теперь метод move_from

2024-03-07 15:56 UTC, etrehappy commented on source/u_forward_list.cpp
> +        std::cout << "Первый элемент контейнера пустой.";
Добавил исключения.

2024-03-07 15:57 UTC, etrehappy commented on source/u_vector.ipp
> +    else if (m_capacity > old_size)
Видимо, был ещё else, но потом убрал его. Исправил.

2024-03-10 09:40 UTC, MarinaPaley commented on source/u_forward_list.h
> +    Node* m_lust_node; //для push_back и end
😄

2024-03-27 16:29 UTC, merged